### ISSUE TITLE
Ansible deployment needs more documentation or an example.

### ISSUE THREAD

**Issue by fghorow** [DrC0ns0le/wg-mesh-dynamic-v2#1]
Nice work! The wg configs generated look good!

For an Ansible newcomer like myself, just having the extras/playbook.yml in your tree isn't quite enough. An example inventory file would be useful -- since when I try to run your playbook using `ansible-playbook -vvv -K -i inventory.yml extra/playbook.yaml`, I get errors of the form:

```
If you are using a module and expect the file to exist on the remote, see the remote_src option
```

I'm sure it's something stupid on my part.

Here's my example inventory.yml (slightly sanitized):

```
all:
  hosts:

    testRouter:
      pipelining: true
      ansible_ssh_user: user1
      ansible_host: "192.168.2.1"
      ansible_ssh_port: 2222

    testWireguardMesh1:
      pipelining: true
      ansible_ssh_user: user1
      ansible_host: "192.168.3.1"
      ansible_ssh_port: 2222

    testWireguardMesh2:
      pipelining: true
      ansible_ssh_user: user1
      ansible_host: "192.168.3.1"
      ansible_ssh_port: 2222
```
